
###
GET http://localhost/api/route-sample/after

<> 2022-07-05T214407.200.json

###
GET http://localhost/api/route-sample/before

###
GET http://localhost/api/route-sample/between

###
GET http://localhost/api/route-sample/cookie
Cookie: cookie=authinfo

<> 2022-07-06T232950.200.json
<> 2022-07-05T215953.200.json

###
GET http://localhost/api/route-sample/header
Authorization: headerInfo

###
GET http://localhost/api/route-sample/remoteAddr

###
GET http://localhost/api/route-sample/query?param=hi

<> 2022-07-06T232749.200.json

### 토큰 발급
POST http://localhost:8081/auth/login
Content-Type: application/json

{
    "id" : "realten",
    "password" : "qwer1234!"
}

### 토큰 값 미입력
GET http://localhost:8000/api/version-check/getVersion

### 토큰 값 입력
GET http://localhost:8000/api/version-check/getVersion
Authorization: Bearer eyJraWQiOiJkYXRhc29sdXRpb24iLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI3MmNkY2MzOS1lMzU4LTRmN2UtYmUzNy01ZWJhMzdkNmJiMTgiLCJpYXQiOjE2NTgxNTkzNDEsImV4cCI6MTY1ODE1OTQ2MX0.ji5q-9d0acALoEvJ1L02Q0hwSYDvzhAi7iZhXSEykiQ
