###
GET http://localhost:8000/api/route-sample/after

###
GET http://localhost:8000/api/route-sample/before

###
GET http://localhost:8000/api/route-sample/between

###
GET http://localhost:8000/api/route-sample/cookie
Cookie: cookie=authinfo

###
GET http://localhost:8000/api/route-sample/header
Authorization: headerInfo

###
POST http://localhost:8000/api/route-sample/method

###
GET http://localhost:8000/api/route-sample/path

###
GET http://localhost:8000/api/route-sample/query?param=hi

### 브라우저에서 실행 필요
GET http://localhost:8000/api/route-sample/remoteAddr

### microservice1 과 microservice2 출력 확인
GET http://localhost:8000/api/route-sample/weight

### 2초 후 Gateway Timeout 발생 확인
GET http://localhost:8000/api/route-sample/timeout


### 토큰 발급
POST http://localhost:8081/auth/login
#POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "id" : "realten",
    "password" : "qwer1234!"
}

### 토큰 값 미입력
GET http://localhost:8000/api/version-check/getVersion

### 토큰 값 입력
GET http://localhost:8000/api/version-check/getVersion
Authorization: Bearer eyJraWQiOiJkYXRhc29sdXRpb24iLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzZmUxMWE4My1lODA1LTQzYzUtODBmOS1lMDAxN2NmNDAyNDYiLCJpYXQiOjE2NTgxNTk2NDUsImV4cCI6MTY1ODE1OTc2NX0.lJZgiYAFBk2DmufzlslrvoIqKkgyRglXZtwiRqDfgUE