server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: foo

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"