spring:
  application:
    name: microservice1
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9091/./scsm
      driver-class-name: org.h2.Driver
      username: sa

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml

server:
  port: 8082
  shutdown: graceful

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info