server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # 해당 인스턴스가 Eureka 서버에 등록해야 하는지에 대한 여부
    fetch-registry: false # 해당 클라이언트가 Eureka 서버에서  Eureka 레지스트리 정보를 가져와야하는지에 대한 여부
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"